import type { RackWireProfile } from './profile-types';

export function createDefaultProfile(): RackWireProfile {
  return {
    id: 'fusion-hci-gen2',
    name: 'Lenovo Fusion HCI Gen 2',
    version: '1.0',
    createdAt: new Date().toISOString(),
    lastModified: new Date().toISOString(),
    isBuiltIn: true,
    rackSize: 42,
    components: {
      SN3700V: {
        id: 'SN3700V', name: 'NVIDIA SN3700V 200GbE ToR RackSwitch', excelId: 'SN3700V',
        size: 1, maxQty: 4, color: '#0078d4',
        category: 'switch', role: 'data-switch',
        ports: [
          { id: 'svc', name: 'P1 (Service Node)', type: 'QSFP28', count: 2 },
          { id: 'breakout-sn2201', name: 'P2 (Mgmt Switch Breakout)', type: 'QSFP28', count: 2 },
          { id: 'data', name: 'P3-P18 (Compute/GPU Data)', type: 'QSFP28', count: 16 },
          { id: 'breakout-pool', name: 'P23-P26 (Breakout to Pool)', type: 'QSFP28', count: 4 },
          { id: 'isl', name: 'P29-P30 (Inter-Switch Link)', type: 'QSFP28', count: 2 },
          { id: 'mgmt', name: 'MGMT', type: 'RJ45', count: 1 },
          { id: 'serial', name: 'SERIAL', type: 'SERIAL', count: 1 },
        ],
      },
      SN2201: {
        id: 'SN2201', name: 'NVIDIA SN2201 1GbE Mgmt RackSwitch', excelId: 'SN2201',
        size: 1, maxQty: 4, color: '#10b981',
        category: 'switch', role: 'mgmt-switch',
        ports: [
          { id: 'pool-mgmt', name: 'P1-P16 (Pool Node MGMT)', type: 'RJ45', count: 16 },
          { id: 'pdu', name: 'P27-P32 (PDU MGMT)', type: 'RJ45', count: 6 },
          { id: 'svc-p33', name: 'P33 (Service Node)', type: 'RJ45', count: 1 },
          { id: 'svc-p35', name: 'P35 (Service Node)', type: 'RJ45', count: 1 },
          { id: 'uplink-p46', name: 'P46 (CE Laptop)', type: 'RJ45', count: 1 },
          { id: 'sn3700v-link', name: 'P49-P50 (SN3700V Breakout)', type: 'SFP28', count: 2 },
          { id: 'isl', name: 'P51-P52 (Inter-Switch Link)', type: 'SFP28', count: 2 },
          { id: 'mgt', name: 'MGT', type: 'RJ45', count: 1 },
        ],
      },
      SR630_SERVICE: {
        id: 'SR630_SERVICE', name: 'Service Node - Lenovo SR630 V3', excelId: 'Service Node',
        size: 1, maxQty: 4, color: '#f97316',
        category: 'server', role: 'service-node',
        ports: [
          { id: 'mgmt', name: 'MGMT', type: 'RJ45', count: 1 },
          { id: 'imm', name: 'IMM', type: 'RJ45', count: 1 },
          { id: 'p1imm', name: 'P1 IMM', type: 'RJ45', count: 1 },
          { id: 'p2imm', name: 'P2 IMM', type: 'RJ45', count: 1 },
          { id: 'p3imm', name: 'P3 IMM', type: 'RJ45', count: 1 },
          { id: 'ocp-p1', name: 'OCP-P1', type: 'RJ45', count: 1 },
          { id: 'ocp-p3', name: 'OCP-P3', type: 'RJ45', count: 1 },
          { id: 'c1-p1', name: 'C1-P1', type: 'SFP28', count: 1 },
          { id: 'c1-p2', name: 'C1-P2', type: 'SFP28', count: 1 },
          { id: 'video', name: 'Video P1', type: 'VIDEO', count: 1 },
          { id: 'usb', name: 'USB P1', type: 'USB', count: 1 },
        ],
      },
      SR630_COMPUTE: {
        id: 'SR630_COMPUTE', name: 'Storage/Compute Server - Lenovo SR630 V3', excelId: 'SR630',
        size: 1, maxQty: 16, color: '#8b5cf6',
        category: 'server', role: 'pool-server',
        ports: [
          { id: 'mgmt', name: 'MGMT', type: 'RJ45', count: 1 },
          { id: 'p1imm', name: 'P1 IMM', type: 'RJ45', count: 1 },
          { id: 'ocp-p1', name: 'OCP-P1', type: 'RJ45', count: 1 },
          { id: 'c3-p1', name: 'C3-P1', type: 'QSFP28', count: 1 },
          { id: 'c3-p2', name: 'C3-P2', type: 'QSFP28', count: 1 },
          { id: 'c1-p1', name: 'C1-P1', type: 'SFP28', count: 1 },
          { id: 'c1-p2', name: 'C1-P2', type: 'SFP28', count: 1 },
        ],
      },
      SR675_GPU: {
        id: 'SR675_GPU', name: 'GPU Server - Lenovo SR675 V3', excelId: 'SR675',
        size: 3, maxQty: 6, color: '#ec4899',
        category: 'server', role: 'pool-server',
        ports: [
          { id: 'mgmt', name: 'MGMT', type: 'RJ45', count: 1 },
          { id: 'p1imm', name: 'P1 IMM', type: 'RJ45', count: 1 },
          { id: 'ocp-p1', name: 'OCP-P1', type: 'RJ45', count: 1 },
          { id: 'c15-p1', name: 'C15-P1', type: 'QSFP56', count: 1 },
          { id: 'c15-p2', name: 'C15-P2', type: 'QSFP56', count: 1 },
          { id: 'c20-p1', name: 'C20-P1', type: 'SFP28', count: 1 },
          { id: 'c20-p2', name: 'C20-P2', type: 'SFP28', count: 1 },
        ],
      },
      KVM: {
        id: 'KVM', name: 'KVM Service Console 7316-TF5', excelId: 'KVM',
        size: 1, maxQty: 2, color: '#fbbf24',
        category: 'infrastructure', role: 'kvm',
        ports: [
          { id: 'video', name: 'VIDEO', type: 'VIDEO', count: 1 },
          { id: 'usb', name: 'USB', type: 'USB', count: 1 },
        ],
      },
      PDU: {
        id: 'PDU', name: 'PDU', excelId: 'PDU',
        size: 1, maxQty: 12, color: '#ef4444',
        category: 'infrastructure', role: 'pdu',
        ports: [
          { id: 'mgmt', name: 'MGMT', type: 'RJ45', count: 1 },
          { id: 'power', name: 'P1', type: 'RJ45', count: 1 },
        ],
      },
      FILLER: {
        id: 'FILLER', name: '1U Filler', excelId: 'Filler',
        size: 1, maxQty: 20, color: '#334155',
        category: 'filler', role: 'filler',
        ports: [],
      },
      RESERVE: {
        id: 'RESERVE', name: 'Reserve', excelId: 'Reserve',
        size: 1, maxQty: 1, color: '#22334d',
        category: 'filler', role: 'filler',
        ports: [],
      },
    },
    cables: {
      'dac-10g-sfp28-1m': {
        id: 'dac-10g-sfp28-1m', name: '1m 10Gb DAC + SFP28/QSFP28 adapter',
        partNumber: '01KL948', connectorType: 'QSFP28→SFP28',
        isBreakout: false, transceiver: '01FT845', sheetTarget: 'mlnx-100gb',
      },
      'breakout-100g-2x50g-1m': {
        id: 'breakout-100g-2x50g-1m', name: 'QSFP28 100GbE to 2x50GbE Breakout 1.0m',
        partNumber: '03MT733', connectorType: 'QSFP28→SFP28',
        isBreakout: true, splitCount: 2, sheetTarget: 'switch-pdu',
      },
      'aoc-100g-qsfp28-3m': {
        id: 'aoc-100g-qsfp28-3m', name: '3m 100Gb QSFP28 AOC',
        partNumber: '01FT722', connectorType: 'QSFP28',
        isBreakout: false, sheetTarget: 'mlnx-100gb',
      },
      'aoc-200g-qsfp56-5m': {
        id: 'aoc-200g-qsfp56-5m', name: '5m 200Gb QSFP56 AOC',
        partNumber: '01FT683', connectorType: 'QSFP56',
        isBreakout: false, sheetTarget: 'mlnx-100gb',
      },
      'breakout-qsfp28-4xsfp28-2m': {
        id: 'breakout-qsfp28-4xsfp28-2m', name: 'QSFP28 to 4x SFP28 25GbE Breakout DAC 2.0m',
        partNumber: '01FT739', connectorType: 'QSFP28→SFP28',
        isBreakout: true, splitCount: 4, sheetTarget: 'mlnx-100gb',
      },
      'dac-100g-qsfp28-05m': {
        id: 'dac-100g-qsfp28-05m', name: '0.5m 100Gb QSFP28 DAC',
        partNumber: '01FT718', connectorType: 'QSFP28',
        isBreakout: false, sheetTarget: 'switch-pdu',
      },
      'cat5e-green-06m': {
        id: 'cat5e-green-06m', name: '0.6m CAT5e RJ45 Green',
        partNumber: '01AF210', connectorType: 'RJ45',
        isBreakout: false, sheetTarget: 'switch-pdu',
      },
      'cat5e-blue-1g': {
        id: 'cat5e-blue-1g', name: 'CAT5e 1GbE Blue',
        partNumber: '01AF039', connectorType: 'RJ45',
        isBreakout: false, sheetTarget: 'etn-ntw',
      },
      'etn-black': {
        id: 'etn-black', name: 'ETN Network Black',
        partNumber: '01AF054', connectorType: 'RJ45',
        isBreakout: false, sheetTarget: 'etn-ntw',
      },
      'cat5e-pdu-3m': {
        id: 'cat5e-pdu-3m', name: 'CAT5e 1GbE PDU 3m',
        partNumber: '01AF040', connectorType: 'RJ45',
        isBreakout: false, sheetTarget: 'switch-pdu',
      },
      'cat5e-1g-generic': {
        id: 'cat5e-1g-generic', name: 'CAT5e 1GbE',
        partNumber: '', connectorType: 'RJ45',
        isBreakout: false, sheetTarget: 'etn-ntw',
      },
      'dac-25g-sfp28-1m': {
        id: 'dac-25g-sfp28-1m', name: '1m 25Gb SFP28 DAC',
        partNumber: '', connectorType: 'SFP28',
        isBreakout: false, sheetTarget: 'mlnx-100gb',
      },
      'kvm-video': {
        id: 'kvm-video', name: 'TF5 Video CBL',
        partNumber: '', connectorType: 'VIDEO',
        isBreakout: false, sheetTarget: 'switch-pdu',
      },
      'kvm-usb': {
        id: 'kvm-usb', name: 'TF5 USB CBL',
        partNumber: '', connectorType: 'USB',
        isBreakout: false, sheetTarget: 'switch-pdu',
      },
    },
    fixedPlacements: [
      { u: 1, componentId: 'RESERVE' },
      { u: 18, componentId: 'SN2201' },
      { u: 19, componentId: 'SN2201' },
      { u: 20, componentId: 'SN3700V' },
      { u: 21, componentId: 'SN3700V' },
      { u: 22, componentId: 'KVM' },
      { u: 23, componentId: 'SR630_SERVICE' },
      { u: 35, componentId: 'PDU' },
      { u: 36, componentId: 'PDU' },
      { u: 37, componentId: 'PDU' },
      { u: 38, componentId: 'PDU' },
      { u: 39, componentId: 'PDU' },
      { u: 40, componentId: 'PDU' },
      { u: 41, componentId: 'PDU' },
      { u: 42, componentId: 'PDU' },
    ],
    presets: [
      {
        gpuCount: 0, label: '0 GPU (16x SR630)',
        placements: [
          ...Array.from({ length: 16 }, (_, i) => ({ u: i + 2, componentId: 'SR630_COMPUTE' })),
          ...Array.from({ length: 11 }, (_, i) => ({ u: i + 24, componentId: 'FILLER' })),
        ],
      },
      {
        gpuCount: 1, label: '1 GPU (1x SR675 + 15x SR630)',
        placements: [
          { u: 2, componentId: 'SR630_COMPUTE' }, { u: 3, componentId: 'SR630_COMPUTE' }, { u: 4, componentId: 'SR630_COMPUTE' },
          { u: 5, componentId: 'SR675_GPU' },
          { u: 8, componentId: 'SR630_COMPUTE' }, { u: 9, componentId: 'SR630_COMPUTE' }, { u: 10, componentId: 'SR630_COMPUTE' },
          { u: 11, componentId: 'SR630_COMPUTE' }, { u: 12, componentId: 'SR630_COMPUTE' }, { u: 13, componentId: 'SR630_COMPUTE' },
          { u: 14, componentId: 'SR630_COMPUTE' }, { u: 15, componentId: 'SR630_COMPUTE' }, { u: 16, componentId: 'SR630_COMPUTE' },
          { u: 17, componentId: 'SR630_COMPUTE' },
          { u: 24, componentId: 'SR630_COMPUTE' }, { u: 25, componentId: 'SR630_COMPUTE' },
          { u: 26, componentId: 'FILLER' }, { u: 27, componentId: 'FILLER' }, { u: 28, componentId: 'FILLER' },
          { u: 29, componentId: 'FILLER' }, { u: 30, componentId: 'FILLER' }, { u: 31, componentId: 'FILLER' },
          { u: 32, componentId: 'FILLER' }, { u: 33, componentId: 'FILLER' }, { u: 34, componentId: 'FILLER' },
        ],
      },
      {
        gpuCount: 2, label: '2 GPU (2x SR675 + 14x SR630)',
        placements: [
          { u: 2, componentId: 'SR630_COMPUTE' }, { u: 3, componentId: 'SR630_COMPUTE' }, { u: 4, componentId: 'SR630_COMPUTE' },
          { u: 5, componentId: 'SR675_GPU' }, { u: 8, componentId: 'SR675_GPU' },
          { u: 11, componentId: 'SR630_COMPUTE' }, { u: 12, componentId: 'SR630_COMPUTE' }, { u: 13, componentId: 'SR630_COMPUTE' },
          { u: 14, componentId: 'SR630_COMPUTE' }, { u: 15, componentId: 'SR630_COMPUTE' }, { u: 16, componentId: 'SR630_COMPUTE' },
          { u: 17, componentId: 'SR630_COMPUTE' },
          { u: 24, componentId: 'SR630_COMPUTE' }, { u: 25, componentId: 'SR630_COMPUTE' },
          { u: 26, componentId: 'SR630_COMPUTE' }, { u: 27, componentId: 'SR630_COMPUTE' },
          { u: 28, componentId: 'FILLER' }, { u: 29, componentId: 'FILLER' }, { u: 30, componentId: 'FILLER' },
          { u: 31, componentId: 'FILLER' }, { u: 32, componentId: 'FILLER' }, { u: 33, componentId: 'FILLER' },
          { u: 34, componentId: 'FILLER' },
        ],
      },
      {
        gpuCount: 3, label: '3 GPU (3x SR675 + 13x SR630)',
        placements: [
          { u: 2, componentId: 'SR630_COMPUTE' }, { u: 3, componentId: 'SR630_COMPUTE' }, { u: 4, componentId: 'SR630_COMPUTE' },
          { u: 5, componentId: 'SR675_GPU' }, { u: 8, componentId: 'SR675_GPU' }, { u: 11, componentId: 'SR675_GPU' },
          { u: 14, componentId: 'SR630_COMPUTE' }, { u: 15, componentId: 'SR630_COMPUTE' },
          { u: 16, componentId: 'SR630_COMPUTE' }, { u: 17, componentId: 'SR630_COMPUTE' },
          { u: 24, componentId: 'SR630_COMPUTE' }, { u: 25, componentId: 'SR630_COMPUTE' },
          { u: 26, componentId: 'SR630_COMPUTE' }, { u: 27, componentId: 'SR630_COMPUTE' },
          { u: 28, componentId: 'SR630_COMPUTE' }, { u: 29, componentId: 'SR630_COMPUTE' },
          { u: 30, componentId: 'FILLER' }, { u: 31, componentId: 'FILLER' }, { u: 32, componentId: 'FILLER' },
          { u: 33, componentId: 'FILLER' }, { u: 34, componentId: 'FILLER' },
        ],
      },
      {
        gpuCount: 4, label: '4 GPU (4x SR675 + 12x SR630)',
        placements: [
          { u: 2, componentId: 'SR630_COMPUTE' }, { u: 3, componentId: 'SR630_COMPUTE' }, { u: 4, componentId: 'SR630_COMPUTE' },
          { u: 5, componentId: 'SR675_GPU' }, { u: 8, componentId: 'SR675_GPU' }, { u: 11, componentId: 'SR675_GPU' },
          { u: 14, componentId: 'SR675_GPU' }, { u: 17, componentId: 'SR630_COMPUTE' },
          { u: 24, componentId: 'SR630_COMPUTE' }, { u: 25, componentId: 'SR630_COMPUTE' },
          { u: 26, componentId: 'SR630_COMPUTE' }, { u: 27, componentId: 'SR630_COMPUTE' },
          { u: 28, componentId: 'SR630_COMPUTE' }, { u: 29, componentId: 'SR630_COMPUTE' },
          { u: 30, componentId: 'SR630_COMPUTE' }, { u: 31, componentId: 'SR630_COMPUTE' },
          { u: 32, componentId: 'FILLER' }, { u: 33, componentId: 'FILLER' }, { u: 34, componentId: 'FILLER' },
        ],
      },
      {
        gpuCount: 5, label: '5 GPU (5x SR675 + 12x SR630)',
        placements: [
          { u: 2, componentId: 'SR630_COMPUTE' }, { u: 3, componentId: 'SR630_COMPUTE' }, { u: 4, componentId: 'SR630_COMPUTE' },
          { u: 5, componentId: 'SR675_GPU' }, { u: 8, componentId: 'SR675_GPU' }, { u: 11, componentId: 'SR675_GPU' },
          { u: 14, componentId: 'SR675_GPU' }, { u: 17, componentId: 'SR630_COMPUTE' },
          { u: 24, componentId: 'SR675_GPU' },
          { u: 27, componentId: 'SR630_COMPUTE' }, { u: 28, componentId: 'SR630_COMPUTE' },
          { u: 29, componentId: 'SR630_COMPUTE' }, { u: 30, componentId: 'SR630_COMPUTE' },
          { u: 31, componentId: 'SR630_COMPUTE' }, { u: 32, componentId: 'SR630_COMPUTE' },
          { u: 33, componentId: 'SR630_COMPUTE' }, { u: 34, componentId: 'SR630_COMPUTE' },
        ],
      },
      {
        gpuCount: 6, label: '6 GPU (6x SR675 + 9x SR630)',
        placements: [
          { u: 2, componentId: 'SR630_COMPUTE' }, { u: 3, componentId: 'SR630_COMPUTE' }, { u: 4, componentId: 'SR630_COMPUTE' },
          { u: 5, componentId: 'SR675_GPU' }, { u: 8, componentId: 'SR675_GPU' }, { u: 11, componentId: 'SR675_GPU' },
          { u: 14, componentId: 'SR675_GPU' }, { u: 17, componentId: 'SR630_COMPUTE' },
          { u: 24, componentId: 'SR675_GPU' }, { u: 27, componentId: 'SR675_GPU' },
          { u: 30, componentId: 'SR630_COMPUTE' }, { u: 31, componentId: 'SR630_COMPUTE' },
          { u: 32, componentId: 'SR630_COMPUTE' }, { u: 33, componentId: 'SR630_COMPUTE' },
          { u: 34, componentId: 'SR630_COMPUTE' },
        ],
      },
    ],
    connectionRules: [
      {
        id: 'sn3700v-to-service-node',
        fromComponent: 'SN3700V', fromPort: 'P1',
        toComponent: 'SR630_SERVICE', toPort: 'C1-P1/P2',
        cableId: 'dac-10g-sfp28-1m',
        cableType: '1m 10Gb DAC + SFP28/QSFP28 adapter', cablePN: '01KL948',
        portType: 'QSFP28→SFP28', transceiver: '01FT845',
      },
      {
        id: 'sn3700v-to-sn2201-breakout',
        fromComponent: 'SN3700V', fromPort: 'P2/1, P2/2',
        toComponent: 'SN2201', toPort: 'P49, P50',
        cableId: 'breakout-100g-2x50g-1m',
        cableType: 'QSFP28 100GbE to 2x50GbE Breakout 1.0m', cablePN: '03MT733',
        portType: 'QSFP28→SFP28', transceiver: '', splitCount: 2,
      },
      {
        id: 'sn3700v-data-to-pool-compute',
        fromComponent: 'SN3700V', fromPort: 'P3-P18',
        toComponent: 'SR630_COMPUTE', toPort: 'C3-P1/P2',
        cableId: 'aoc-100g-qsfp28-3m',
        cableType: '3m 100Gb QSFP28 AOC', cablePN: '01FT722',
        portType: 'QSFP28', transceiver: '',
      },
      {
        id: 'sn3700v-data-to-pool-gpu',
        fromComponent: 'SN3700V', fromPort: 'P3-P18',
        toComponent: 'SR675_GPU', toPort: 'C15-P1/P2',
        cableId: 'aoc-200g-qsfp56-5m',
        cableType: '5m 200Gb QSFP56 AOC', cablePN: '01FT683',
        portType: 'QSFP56', transceiver: '',
      },
      {
        id: 'sn3700v-breakout-to-pool-compute',
        fromComponent: 'SN3700V', fromPort: 'P23-P26 (4x breakout)',
        toComponent: 'SR630_COMPUTE', toPort: 'C1-P1/P2',
        cableId: 'breakout-qsfp28-4xsfp28-2m',
        cableType: 'QSFP28 to 4x SFP28 25GbE Breakout DAC 2.0m', cablePN: '01FT739',
        portType: 'QSFP28→SFP28', transceiver: '', splitCount: 4,
      },
      {
        id: 'sn3700v-breakout-to-pool-gpu',
        fromComponent: 'SN3700V', fromPort: 'P23-P26 (4x breakout)',
        toComponent: 'SR675_GPU', toPort: 'C20-P1/P2',
        cableId: 'breakout-qsfp28-4xsfp28-2m',
        cableType: 'QSFP28 to 4x SFP28 25GbE Breakout DAC 2.0m', cablePN: '01FT739',
        portType: 'QSFP28→SFP28', transceiver: '', splitCount: 4,
      },
      {
        id: 'sn3700v-isl',
        fromComponent: 'SN3700V', fromPort: 'P29, P30',
        toComponent: 'SN3700V', toPort: 'P29, P30 (peer)',
        cableId: 'dac-100g-qsfp28-05m',
        cableType: '0.5m 100Gb QSFP28 DAC', cablePN: '01FT718',
        portType: 'QSFP28', transceiver: '',
      },
      {
        id: 'sn3700v-mgmt-link',
        fromComponent: 'SN3700V', fromPort: 'MGMT',
        toComponent: 'SN3700V', toPort: 'MGMT (peer)',
        cableId: 'cat5e-green-06m',
        cableType: '0.6m CAT5e RJ45 Green', cablePN: '01AF210',
        portType: 'RJ45', transceiver: '',
      },
      {
        id: 'sn2201-to-pool-mgmt',
        fromComponent: 'SN2201', fromPort: 'P1-P16',
        toComponent: 'Pool Node', toPort: 'MGMT',
        cableId: 'cat5e-blue-1g',
        cableType: 'CAT5e 1GbE Blue', cablePN: '01AF039',
        portType: 'RJ45', transceiver: '',
      },
      {
        id: 'sn2201-to-pool-imm',
        fromComponent: 'SN2201', fromPort: 'P1-P16',
        toComponent: 'Pool Node', toPort: 'P1 IMM',
        cableId: 'etn-black',
        cableType: 'ETN Network Black', cablePN: '01AF054',
        portType: 'RJ45', transceiver: '',
      },
      {
        id: 'sn2201-to-pdu',
        fromComponent: 'SN2201', fromPort: 'P27-P32',
        toComponent: 'PDU', toPort: 'MGMT',
        cableId: 'cat5e-pdu-3m',
        cableType: 'CAT5e 1GbE PDU 3m', cablePN: '01AF040',
        portType: 'RJ45', transceiver: '',
      },
      {
        id: 'sn2201-to-service-mgmt',
        fromComponent: 'SN2201', fromPort: 'P33',
        toComponent: 'SR630_SERVICE', toPort: 'MGMT / P1 IMM / OCP-P1',
        cableId: 'cat5e-1g-generic',
        cableType: 'CAT5e 1GbE', cablePN: '',
        portType: 'RJ45', transceiver: '',
      },
      {
        id: 'sn2201-to-service-ssh',
        fromComponent: 'SN2201', fromPort: 'P35',
        toComponent: 'SR630_SERVICE', toPort: 'P2 IMM / P3 IMM / OCP-P3',
        cableId: 'cat5e-1g-generic',
        cableType: 'CAT5e 1GbE', cablePN: '',
        portType: 'RJ45', transceiver: '',
      },
      {
        id: 'sn2201-isl',
        fromComponent: 'SN2201', fromPort: 'P51, P52',
        toComponent: 'SN2201', toPort: 'P51, P52 (peer)',
        cableId: 'dac-25g-sfp28-1m',
        cableType: '1m 25Gb SFP28 DAC', cablePN: '',
        portType: 'SFP28', transceiver: '',
      },
      {
        id: 'sn2201-to-sn3700v',
        fromComponent: 'SN2201', fromPort: 'P49, P50',
        toComponent: 'SN3700V', toPort: 'P2/1, P2/2',
        cableId: 'breakout-100g-2x50g-1m',
        cableType: 'QSFP28 100GbE to 2x50GbE Breakout', cablePN: '03MT733',
        portType: 'SFP28→QSFP28', transceiver: '',
      },
      {
        id: 'kvm-video',
        fromComponent: 'KVM', fromPort: 'VIDEO',
        toComponent: 'SR630_SERVICE', toPort: 'Video P1',
        cableId: 'kvm-video',
        cableType: 'TF5 Video CBL', cablePN: '',
        portType: 'VIDEO', transceiver: '',
      },
      {
        id: 'kvm-usb',
        fromComponent: 'KVM', fromPort: 'USB',
        toComponent: 'SR630_SERVICE', toPort: 'USB P1',
        cableId: 'kvm-usb',
        cableType: 'TF5 USB CBL', cablePN: '',
        portType: 'USB', transceiver: '',
      },
      {
        id: 'sn2201-mgmt-green',
        fromComponent: 'SN2201', fromPort: 'MGMT',
        toComponent: 'SN2201', toPort: 'MGMT (peer)',
        cableId: 'cat5e-green-06m',
        cableType: 'GREEN ETN 0.6M', cablePN: '01AF210',
        portType: 'RJ45', transceiver: '',
      },
    ],
    excelSheets: [
      { id: 'labels-p2p', name: 'Labels (P2P)', description: 'Point-to-point cable listing with color coding', enabled: true, footerPN: '', footerEC: '' },
      { id: 'server-layout', name: 'Server Layout', description: 'Rack layout diagram in spreadsheet form', enabled: true, footerPN: '', footerEC: '' },
      { id: 'etn-ntw', name: 'ETN NTW', description: 'Ethernet Network cable labels (SN2201 management)', enabled: true, footerPN: '', footerEC: '' },
      { id: 'switch-pdu', name: 'Switch&PDU', description: 'Switch inter-links, PDU cables, KVM connections', enabled: true, footerPN: '', footerEC: '' },
      { id: 'mlnx-100gb', name: 'MLNX 100GB', description: 'Mellanox 100Gb AOC data cables and breakout labels', enabled: true, footerPN: '', footerEC: '' },
    ],
    etnRules: {
      sw1Header: [
        { condition: { gpuMin: 0, gpuMax: 3 }, cableType: 'U2 ETN BLUE', cablePn: '01AF039 ' },
        { condition: { gpuMin: 4, gpuMax: 6 }, cableType: '1.5M ETN BLUE', cablePn: '01AF039 ' },
      ],
      sw2Header: [
        { condition: { gpuMin: 0, gpuMax: 3 }, cableType: 'ETN Network Black', cablePn: '01AF054 ' },
        { condition: { gpuMin: 4, gpuMax: 6 }, cableType: '1.5M ETN BLUE', cablePn: '01AF039 ' },
      ],
      sw1Short: [
        { condition: { gpuMin: 0, gpuMax: 6 }, cableType: '1M ETN Blue', cablePn: '01KL931' },
      ],
      sw2Short: [
        { condition: { gpuMin: 0, gpuMax: 2 }, cableType: '1M ETN Yellow', cablePn: '01KL755' },
        { condition: { gpuMin: 3, gpuMax: 6 }, cableType: '1M ETN Blue', cablePn: '01KL931' },
      ],
      sw2ServerPort: [
        { condition: { gpuMin: 0, gpuMax: 1 }, value: 'P1 IMM' },
        { condition: { gpuMin: 2, gpuMax: 6 }, value: 'OCP-P1' },
      ],
      sw2ServicePorts: [
        { condition: { gpuMin: 0, gpuMax: 1 }, p33: 'P1 IMM', p35: 'P3 IMM' },
        { condition: { gpuMin: 2, gpuMax: 3 }, p33: 'OCP-P1', p35: 'OCP-P3' },
        { condition: { gpuMin: 4, gpuMax: 6 }, p33: 'P1 IMM', p35: 'P3 IMM' },
      ],
    },
    mlnxRules: {
      aocCable: { type: 'QSFP28 (100Gb)', partNumber: '01FT722', description: '3m 100Gb QSFP28 AOC' },
      gpuAocCable: { type: 'QSFP56 (200Gb)', partNumber: '01FT683', description: '5m 200Gb QSFP56 AOC' },
      breakoutCable: { type: 'QSFP28 (100Gb)', partNumber: '01FT739 x1', description: 'QSFP28 to 4x SFP28 25GbE Breakout DAC 2.0m' },
      serviceNodeSfpCable: { type: '10GB SFP Cable 1M', partNumber: '01KL948 x2', description: '10Gb SFP28 DAC' },
      computeChassisSlot: 'C3',
      gpuChassisSlot: 'C15',
      breakoutComputeSlot: 'C1',
      breakoutGpuSlot: 'C20',
    },
    switchPduRules: {
      pduCable: { type: 'CABLE Ethern \n3m Blue PDU', partNumber: '01AF040', description: '3m CAT5e Blue PDU cable' },
      sn2201InterLink: { type: 'QSFP28 (100Gb) 0.5m', partNumber: '01FT718 x2', description: '0.5m QSFP28 DAC inter-switch' },
      sn3700vInterLink: { type: 'QSFP28 (100Gb) 0.5m', partNumber: '01FT718 x2', description: '0.5m QSFP28 DAC inter-switch' },
      greenEtnCable: { type: 'GREEN ETN 0.6M', partNumber: '01AF210x1', description: '0.6m CAT5e Green management' },
      sn3700vBreakoutCable: { type: 'QSFP28 (100Gb)', partNumber: '03MT733 x1', description: 'QSFP28 100GbE to 2x50GbE Breakout' },
      kvmVideoCable: 'TF5 Video CBL',
      kvmUsbCable: 'TF5 USB CBL',
      serviceNodeLabel: 'SR645 6',
    },
  };
}
